### ISSUE TITLE
Completion block / closure never fires when using m_animate

### ISSUE THREAD

**Issue by mitchellporter** [lkzhao/MotionAnimation#1]
Hey Luke,

First off thanks for releasing this library I love the way the motion looks. It's my new favorite animation library :)

I'm using a pan gesture to allow the user to move an object around the screen. I noticed that none of the completion blocks / closures were firing so I started adding breakpoints to your library. For some reason the code just keeps running, even after the animation has finished on the screen.

I can't seem to figure out why it keeps running and never wants to stop. Any chance I can get your help on this? Thanks.

**Comment by lkzhao** [comment]
I have a new version with many bug fixes and perf optimization for this soon. In the mean time try setting MotionAnimator.sharedInstance.debugEnabled to true and see if the animator actually stops when your animation ends.

**Comment by mitchellporter** [comment]
@lkzhao Hey Luke I figured it out after a few hours of banging my head against the wall :)

I looked over your example code for any differences I could find and I noticed you were setting the `threshold` parameter to `1`. I had been setting all of mine to zero which was causing the animations to run forever. Even just applying a `threshold` of `0.1` fixes the problem, so nothing wrong with your code, it was purely my fault.

I wanted to say thanks again for creating this. I'm a huge fan of realistic motion animations and a lot of the animation libraries available, including `Facebook POP`, feel very cluttered.

I love the simplicity of this library. Please let me know if you ever need any help or feedback.

Cheers ;)

**Comment by mitchellporter** [comment]
> I have a new version with many bug fixes and perf optimization for this soon.

Also, I'd be happy to test this out for you if you want. Thanks again for the help!

**Comment by lkzhao** [comment]
@mitchellporter 
I should have raised an warning about setting `threshold` to zero. I will include that in the upcoming release.
Basically the `threshold` determines when the sprint animation terminates. When the difference between target/current value and the velocity drop within the threshold, the spring animation stops.

Thank you for being an early adopter though. I also use this library in one of my upcoming app and noticed some performance problems. There is also a lot of hard-to-read code just to support animating objective-c KVO properties.

So I am thinking about deprecating these two files.
- MotionAnimationPropertyState.swift
- NSObject+MotionAnimation.swift
  Because they add a lot of complexity and performance hit.

For the most part, this library is working elegantly with the following four classes:
- MotionAnimator
- MotionAnimation
- ValueAnimation
- SpringValueAnimation

If you look into `UIView+MotionAnimation.swift` file you can see a custom animation `PositionAnimation` built to animate a CGPoint property. I tested it against the m_animate version and found that it is many times faster. 

Right now I am still thinking about a clever way to animate any values without creating a custom animation and losing performance. Stay tuned.
